[package]
name = "rust_lib_frb_sqlite"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.0.0-dev.28"
sqlx = { version = "0.7.4", features = ["sqlite"] }
tokio = { version = "1.36.0", features = ["full"] }
